language: go

go:
  - "1.10.x"

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - mkdir -p $GOPATH/src/github.com/Haraguroicha
  - ln -s $PWD $GOPATH/src/github.com/Haraguroicha/cs-codingchallenge

install:
  - dep ensure -v -vendor-only

script:
  - make test
